trigger:
  branches:
    include:
    - main
  paths:
    include:
      - applications/observability/**
  batch: true
pr: none
extends:
  template: ../templates/apply-module.yml
  parameters:
    moduleName: Observability stack
    modulePath: applications/observability
