trigger:
  branches:
    include:
    - main
  paths:
    include:
      - applications/clusters/redcliff/**
      - applications/modules/**
  batch: true
pr: none

extends:
  template: ../templates/apply-module.yml
  parameters:
    moduleName: Redcliff - Applications
    modulePath: applications/clusters/redcliff
