pr:
  branches:
    include:
      - main
  paths:
    include:
      - applications/modules/**
      - applications/clusters/test/**

pool: Self hosted

variables:
- group: terraform

steps:
- script: |
    set -e
    terraform init
    terraform plan -input=false -refresh=false -detailed-exitcode
    EXIT_CODE=$?
    echo "##vso[task.setvariable variable=TF_PLAN_EXIT_CODE_TEST]$EXIT_CODE"
  displayName: 'Terraform Init and Plan (no refresh)'
  workingDirectory: applications/clusters/test
  env:
    AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
    AUTHENTIK_TOKEN: $(AUTHENTIK_TOKEN)
    MINIO_PASSWORD: $(MINIO_PASSWORD)
    CLOUDFLARE_API_TOKEN: $(CLOUDFLARE_API_TOKEN)
    RANCHER_TOKEN_KEY: $(RANCHER_TOKEN_KEY)
    TF_VAR_domain: $(TF_VAR_domain)
    TF_VAR_secondary_domain: $(TF_VAR_secondary_domain)
    TF_VAR_windows_domain: $(TF_VAR_windows_domain)
    TF_VAR_cloudflare_email: $(TF_VAR_cloudflare_email)
    TF_VAR_cloudflare_api_key: $(TF_VAR_cloudflare_api_key)

- task: GitHubComment@0
  displayName: 'Post Terraform Plan Changes Comment'
  inputs:
    gitHubConnection: 'rhysj6'
    comment: 'Detected changes for test cluster.'
  condition: eq(variables['TF_PLAN_EXIT_CODE_TEST'], '2')

