pr:
  branches:
    include:
      - main
  paths:
    include:
      - applications/modules/**
      - applications/clusters/**
      - applications/observability/**

pool: Self hosted
stages:
- stage: ModuleChangeDetection
  displayName: 'Application cluster change detection'
  variables:
  - group: terraform
  jobs:
  - job: ModulePlan
    strategy:
      matrix:
        Test:
          MODULE_NAME: test
          MODULE_PATH: applications/clusters/test
        Redcliff:
          MODULE_NAME: redcliff
          MODULE_PATH: applications/clusters/redcliff
        Management:
          MODULE_NAME: management
          MODULE_PATH: applications/clusters/management
        Observability:
          MODULE_NAME: observability
          MODULE_PATH: applications/observability
          NOTIFY: false
    steps:
    - script: |
        set -e
        terraform init
      displayName: 'Terraform Init'
      workingDirectory: $(MODULE_PATH)
      env:
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)

    - script: |
        terraform plan -input=false -refresh=false -detailed-exitcode || EXIT_CODE=$?
        if [ -z "$EXIT_CODE" ]; then EXIT_CODE=0; fi
        if [ "$EXIT_CODE" -eq 1 ]; then
          echo "Terraform plan failed with error code 1. Failing the pipeline."
          exit 1
        fi
        echo "##vso[task.setvariable variable=TF_PLAN_EXIT_CODE]$EXIT_CODE"
      displayName: 'Terraform Plan (no refresh)'
      workingDirectory: $(MODULE_PATH)
      env:
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
        AUTHENTIK_TOKEN: $(AUTHENTIK_TOKEN)
        MINIO_PASSWORD: $(MINIO_PASSWORD)
        CLOUDFLARE_API_TOKEN: $(CLOUDFLARE_API_TOKEN)
        RANCHER_TOKEN_KEY: $(RANCHER_TOKEN_KEY)
        TF_VAR_domain: $(TF_VAR_domain)
        TF_VAR_secondary_domain: $(TF_VAR_secondary_domain)
        TF_VAR_windows_domain: $(TF_VAR_windows_domain)
        TF_VAR_cloudflare_email: $(TF_VAR_cloudflare_email)
        TF_VAR_cloudflare_api_key: $(TF_VAR_cloudflare_api_key)

    - task: GitHubComment@0
      displayName: 'Post Terraform Plan Changes Comment'
      inputs:
        gitHubConnection: 'rhysj6'
        comment: 'Detected changes for $(MODULE_NAME) module.'
      condition: and(eq(variables['TF_PLAN_EXIT_CODE'], '2'), ne(variables['NOTIFY'], 'false'))

