pr:
  branches:
    include:
      - main
  paths:
    include:
      - applications/modules/**
      - applications/clusters/test/**

pool: Self hosted

variables:
- group: terraform

steps:
- script: |
    terraform init
    terraform plan -refresh=false -detailed-exitcode
    EXIT_CODE=$?
    echo "##vso[task.setvariable variable=TF_PLAN_EXIT_CODE_TEST]$EXIT_CODE"
  displayName: 'Terraform Init and Plan (no refresh)'
  workingDirectory: applications/clusters/test

- task: GitHubComment@0
  displayName: 'Post Terraform Plan Success Comment'
  inputs:
    gitHubConnection: '$(githubServiceConnection)'
    repositoryName: '$(Build.Repository.Name)'
    pullRequestId: '$(System.PullRequest.PullRequestId)'
    comment: 'Terraform plan succeeded and no changes are required.'
  condition: eq(variables['TF_PLAN_EXIT_CODE'], '0')

- task: GitHubComment@0
  displayName: 'Post Terraform Plan Changes Comment'
  inputs:
    gitHubConnection: 'rhysj6'
    comment: 'Detected changes for test cluster.'
  condition: eq(variables['TF_PLAN_EXIT_CODE'], '2')