pr:
  branches:
    include:
      - main
  paths:
    include:
      - applications/clusters/management/**
      - applications/modules/**

pool: Self hosted
stages:
- stage: ManagementModuleChangeDetection
  displayName: 'Management module change detection'
  variables:
  - group: terraform
  jobs:
  - template: ../templates/module-change-detection.yml
    parameters:
      moduleName: Management - Applications
      modulePath: applications/clusters/management
      notify: true
      comment: 'Detected changes for management cluster.'
