pr:
  branches:
    include:
      - main
  paths:
    include:
      - applications/observability/**

pool: Self hosted
stages:
- stage: ObservabilityModuleChangeDetection
  displayName: 'Observability module change detection'
  variables:
  - group: terraform
  jobs:
  - template: ../templates/module-change-detection.yml
    parameters:
      moduleName: Observability stack
      modulePath: applications/observability
      notify: false
      comment: 'Detected changes for observability module.'
