pr:
  branches:
    include:
      - main
  paths:
    include:
      - applications/clusters/redcliff/**
      - applications/modules/**

pool: Self hosted
stages:
- stage: RedcliffModuleChangeDetection
  displayName: 'Redcliff module change detection'
  variables:
  - group: terraform
  jobs:
  - template: ../templates/module-change-detection.yml
    parameters:
      moduleName: Redcliff - Applications
      modulePath: applications/clusters/redcliff
      notify: true
