pr:
  branches:
    include:
      - main
  paths:
    include:
      - applications/clusters/test/**
      - applications/modules/**

pool: Self hosted
stages:
- stage: TestModuleChangeDetection
  displayName: 'Test module change detection'
  variables:
  - group: terraform
  jobs:
  - template: ../templates/module-change-detection.yml
    parameters:
      moduleName: Test - Applications
      modulePath: applications/clusters/test
      notify: true
