apiVersion: 1
datasources:
    - name: "Prometheus"
      type: prometheus
      uid: prometheus
      url: http://prometheus-prometheus.monitoring.svc.cluster.local:9090/
      access: proxy
      jsonData:
        httpMethod: POST
        timeInterval: 30s
    - name: "Alertmanager"
      type: alertmanager
      uid: alertmanager
      url: http://prometheus-alertmanager.monitoring.svc.cluster.local:9093/
      access: proxy
      jsonData:
        handleGrafanaManagedAlerts: false
        implementation: "prometheus"
