
alloy:
  configMap:
    create: false
    name: alloy-config
    key: .
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
extraPorts:
  - name: otlp-grpc
    port: 4317
    protocol: TCP
  - name: otlp-http
    port: 4318
    protocol: TCP
controller:
  type: deployment
  replicas: 1
  autoscaling:
    enabled: true
service:
  type: LoadBalancer