
kubeproxyReplacement: true
k8sServicePort: 6443
externalIPs:
  enabled: true

l2announcements:
  enabled: true

k8sClientRateLimit:
  burst: 128
  qps: 64

ipam:
  operator:
    clusterPoolIPv4PodCIDRList:
      - "10.42.0.0/16"

ingressController:
  enabled: true
  default: true
  loadBalancerMode: "shared"
  enforceHttps: true

gatewayAPI:
  enabled: true
  default: true