trigger:
  branches:
    include:
    - main
  paths:
    include:
      - clusters/management/core/**
      - modules/core_cluster/**
  batch: true
pr: none

extends:
  template: ../templates/apply-module.yml
  parameters:
    moduleName: Management - Core cluster
    modulePath: clusters/management/core
    kubeConfigSecureFile: 'management-kubeconfig'
