trigger:
  branches:
    include:
    - main
    - test
  paths:
    include:
      - clusters/test/core/**
      - modules/core_cluster/**
  batch: true
pr: none

extends:
  template: ../templates/apply-module.yml
  parameters:
    moduleName: test
    modulePath: clusters/test/core
