pr:
  branches:
    include:
      - main
  paths:
    include:
      - clusters/management/**
      - modules/core_cluster/**

pool: Self hosted
stages:
- stage: ManagementModuleChangeDetection
  displayName: 'Management module change detection'
  variables:
  - group: terraform
  jobs:
  - template: ../templates/module-change-detection.yml
    parameters:
      moduleName: Management - Core cluster
      modulePath: clusters/management/core
      notify: true
      kubeConfigSecureFile: 'management-kubeconfig'
