- name: Create ansible user and configure sudo and SSH access if it doesn't exist
  hosts: "*"
  become: true
  roles:
    - role: automation_user 
      vars:
        name: "{{ lookup('infisical_vault', project_id='ansible', path='init/automation_user', env_slug='prod', secret_name='username') }}"
        password: "{{ lookup('infisical_vault', project_id='ansible', path='init/automation_user', env_slug='prod', secret_name='password') }}"
        ssh_key: "{{ lookup('infisical_vault', project_id='ansible', path='init/automation_user', env_slug='prod', secret_name='public_ssh_key') }}"
    - role: passwordless_sudo
      vars:
        my_account: "{{ lookup('infisical_vault', project_id='ansible', path='init', env_slug='prod', secret_name='initial_user') }}"

- name: Install Grafana Alloy on all servers
  hosts: all
  become: true
  roles:
    - role: alloy

- name: Install QEMU guest agent on all VMs
  hosts: vm_servers
  become: true
  tasks:
    - name: Install qemu-guest-agent
      apt:
        name: qemu-guest-agent
        state: present