- name: Create ansible user and configure sudo and SSH access if it doesn't exist
  hosts: "*"
  become: true
  roles:
    - role: automation_user 
      vars:
        name: "{{ automation_user }}"
        password: "{{ automation_user_password }}"
        ssh_key: "{{ automation_user_public_ssh_key }}"
    - role: passwordless_sudo
      vars:
        my_account: "{{ automation_user }}"

- name: Install Grafana Alloy on all servers
  hosts: all
  become: true
  roles:
    - role: alloy


- name: Install QEMU guest agent on all VMs
  hosts: vm_servers
  become: true
  tasks:
    - name: Install qemu-guest-agent
      apt:
        name: qemu-guest-agent
        state: present