- name: Main play for all servers
  hosts: all
  become: true
  roles:
    - role: automation_user
      vars:
        automation_user_name: "{{ lookup('infisical.vault.read_secrets',
          project_id=infisical_project, env_slug=env,
          path='/init/automation_user', secret_name='username'
          ).value }}"
        automation_user_password: "{{ lookup('infisical.vault.read_secrets',
          project_id=infisical_project, env_slug=env,
          path='/init/automation_user', secret_name='password'
          ).value }}"
        automation_user_ssh_key: "{{ lookup('infisical.vault.read_secrets',
          project_id=infisical_project, env_slug=env,
          path='/init/automation_user', secret_name='public_ssh_key'
          ).value }}"
    - role: passwordless_sudo
      vars:
        passwordless_sudo_account: "{{ lookup('infisical.vault.read_secrets',
          project_id=infisical_project, env_slug=env,
          path='/init', secret_name='initial_user'
          ).value }}"
    - role: grafana_alloy

- name: Install QEMU guest agent on all VMs
  hosts: vm_servers
  become: true
  tasks:
    - name: Install qemu-guest-agent
      ansible.builtin.apt:
        name: qemu-guest-agent
        state: present
