apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  name: ${cluster_name}
  namespace: fleet-default
spec:
  kubernetesVersion: ${kubernetes_version}
  localClusterAuthEndpoint: {}
  rkeConfig:
    additionalManifest: |+
      apiVersion: helm.cattle.io/v1
      kind: HelmChart
      metadata:
        name: cilium
        namespace: kube-system
      spec:
        repo: https://helm.cilium.io
        chart: cilium
        targetNamespace: kube-system
        valuesContent: |-
          kubeProxyReplacement: true
          k8sServiceHost: localhost
          k8sServicePort: 6443
          externalIPs:
            enabled: true
          l2announcements:
            enabled: true
          k8sClientRateLimit:
            burst: 128
            qps: 64
          ipam:
            operator:
              clusterPoolIPv4PodCIDRList:
                - "10.42.0.0/16"
    chartValues: {}
    dataDirectories: {}
    etcd:
      s3:
        bucket: ${bucket_name}
        cloudCredentialName: ${cloud_credential_name}
        endpoint: ${s3_endpoint}
      snapshotRetention: 10
      snapshotScheduleCron: 0 */5 * * *
    machineGlobalConfig:
      disable:
        - servicelb
        - traefik
        - local-storage
      disable-apiserver: false
      disable-cloud-controller: false
      disable-controller-manager: false
      disable-etcd: false
      disable-kube-proxy: false
      disable-network-policy: false
      disable-scheduler: false
      etcd-expose-metrics: false
      secrets-encryption: false
      flannelBackend: none
    machinePoolDefaults: {}
    machineSelectorConfig:
      - config:
          docker: false
          protect-kernel-defaults: false
          selinux: false
    registries: {}
    upgradeStrategy:
      controlPlaneConcurrency: '1'
      controlPlaneDrainOptions:
        deleteEmptyDirData: true
        disableEviction: false
        enabled: false
        force: false
        gracePeriod: -1
        ignoreDaemonSets: true
        ignoreErrors: false
        skipWaitForDeleteTimeoutSeconds: 0
        timeout: 120
      workerConcurrency: '1'
      workerDrainOptions:
        deleteEmptyDirData: true
        disableEviction: false
        enabled: false
        force: false
        gracePeriod: -1
        ignoreDaemonSets: true
        ignoreErrors: false
        skipWaitForDeleteTimeoutSeconds: 0
        timeout: 120