- name: Check if mc is installed
  ansible.builtin.command: mc --version
  register: minio_mc_check
  changed_when: false
  ignore_errors: true

- name: Download MinIO client
  ansible.builtin.get_url:
    url: https://dl.min.io/client/mc/release/linux-amd64/mc
    dest: /usr/local/bin/mc
    mode: '0755'
  when: minio_mc_check.rc != 0
  notify:
    - Verify mc installation
