
kubeProxyReplacement: "true"
k8sServiceHost: "10.20.10.11"
k8sServicePort: 6443
externalIPs:
  enabled: true
operator:
  replicas: 1

bgpControlPlane:
  enabled: true

ipam:
  operator:
    clusterPoolIPv4PodCIDRList:
      - "10.42.0.0/16"