apiVersion: v1alpha1
kind: VolumeConfig
name: EPHEMERAL
provisioning:
    grow: false
    maxSize: 16GiB

---

apiVersion: v1alpha1
kind: UserVolumeConfig
name: longhorn
provisioning:
  diskSelector:
    match: system_disk
  minSize: 16GB
  maxSize: 400GB # Adjust later to fit prod nodes

---

machine:
  kubelet:
    extraMounts:
    - destination: /var/mnt/longhorn
      type: bind
      source: /var/mnt/longhorn
      options:
        - bind
        - rshared
        - rw
  sysctls:
    vm.nr_hugepages: "1024"
  kernel:
    modules:
      - name: nvme_tcp
      - name: vfio_pci