apiVersion: v1
kind: Pod
spec:
  containers:
  - name: ansible
    image: rhysj6/ansible-agent:latest
    securityContext:
      runAsUser: 0
    tty: true
    command: ["/bin/sh", "-c", "while true; do sleep 30; done;"]