
alloy:
  configMap:
    create: false
    name: alloy-config
    key: .
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
controller:
  type: deployment
  replicas: 1
  autoscaling:
    enabled: true