global:
  dnsService: rke2-coredns-rke2-coredns

loki:
  commonConfig:
    replication_factor: 1
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  pattern_ingester:
      enabled: true
  limits_config:
    allow_structured_metadata: true
    volume_enabled: true
    retention_period: 672h # 28 days retention

  storage:
    type: s3
    bucketNames:
        chunks: ${BUCKET_PREFIX}-chunks
        ruler: ${BUCKET_PREFIX}-ruler
        admin: ${BUCKET_PREFIX}-admin
    s3:
      # AWS endpoint URL
      endpoint: ${S3_ENDPOINT}
      # AWS secret access key
      secretAccessKey: ${S3_SECRET_ACCESS_KEY}
      # AWS access key ID
      accessKeyId: ${S3_ACCESS_KEY_ID}
      s3ForcePathStyle: true
  
  tenants:
    - name: onsite-production
      password: ${BASIC_AUTH_PASSWORD}
    - name: test
      password: ${BASIC_AUTH_PASSWORD}

deploymentMode: SingleBinary

gateway:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: cert-manager
    hosts:
      - host: ${INGRESS_HOST}
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: loki-gateway-tls
        hosts:
          - ${INGRESS_HOST}


# Disable minio storage
minio:
  enabled: false

singleBinary:
  replicas: 1

# Zero out replica counts of other deployment modes
backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0