---
- name: Create ansible user and configure sudo and SSH access if it doesn't exist
  hosts: "*"
  become: true
  tasks:
    - name: Create a login user
      user:
        name: ansible
        password: "{{ automation_user_password | password_hash('sha512') }}"
        groups:
          - sudo
        state: present

    - name: Add SSH key to ansible user
      authorized_key:
        user: ansible
        key: "{{ automation_user_public_ssh_key }}"
        state: present

    - name: Enable passwordless sudo for ansible user
      copy:
        dest: /etc/sudoers.d/{{ automation_user }}
        content: "{{ automation_user }} ALL=(ALL) NOPASSWD:ALL\n"
        mode: "0440"
    - name: Enable passwordless sudo for initial user
      copy:
        dest: /etc/sudoers.d/{{ initial_user }}
        content: "{{ initial_user }} ALL=(ALL) NOPASSWD:ALL\n"
        mode: "0440"
- name: Install Grafana Alloy on all servers
  hosts: all
  become: true
  tasks:
    - name: Ensure /etc/alloy directory exists
      file:
        path: /etc/alloy
        state: directory
        mode: "0755"
    - name: Copy Alloy config file
      become: true
      ansible.builtin.template:
        src: config.alloy
        dest: /etc/alloy/default.alloy
        mode: "0644"
    - name: Install Alloy
      ansible.builtin.include_role:
        name: grafana.grafana.alloy
      vars:
        alloy_env_file_vars:
          CONFIG_FILE: /etc/alloy/default.alloy


- name: Install QEMU guest agent on all VMs
  hosts: vm_servers
  become: true
  tasks:
    - name: Install qemu-guest-agent
      apt:
        name: qemu-guest-agent
        state: present