- name: Main play for all servers
  hosts: all
  roles:
    - role: automation_user
    - role: passwordless_sudo
      vars:
        passwordless_sudo_account: "{{ lookup('infisical.vault.read_secrets',
          project_id=infisical_project, env_slug=env,
          path='/init', secret_name='initial_user'
          ).value }}"
    - role: grafana_alloy

- name: Install QEMU guest agent on all VMs
  hosts: vm_servers
  tasks:
    - name: Install qemu-guest-agent
      ansible.builtin.apt:
        name: qemu-guest-agent
        state: present
