- name: Ensure /etc/alloy directory exists
  file:
    path: /etc/alloy
    state: directory
    mode: "0755"
    owner: root
    group: alloy

- name: Copy Alloy config file
  ansible.builtin.template:
    src: config.alloy.j2
    dest: /etc/alloy/default.alloy
    mode: "0644"